config/routes.rb
Rails.application.routes.draw do
  get 'enrollments/index'
  get 'enrollments/new'
  post 'enrollments/create'
  delete 'enrollments/destroy'
  get 'courses/index'
  get 'courses/new'
  post 'courses/create'
  get 'courses/show'
  get 'courses/edit'
  patch 'courses/update'
  get 'courses/destroy'
  get 'students/index'
  get 'students/new'
  post 'students/create'
  get 'students/show'
  get 'students/edit'
  patch 'students/update'
  get 'students/destroy'
  # student_index => 'student/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
    has_many :enrollments
    has_many :students, through: :enrollments
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
    belongs_to :student
    belongs_to :course
end

app/models/student.rb
class Student < ApplicationRecord
    has_many:enrollments
    has_many:courses, through: :enrollments
    validates :full_name,presence:true
    validates :id_num,presence:true
    validates :sex,presence:true
    validates :department,presence:true
    validates :compus,presence:true
    validates :dob,presence:true
    validates :id_num,uniqueness:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses =Course.all
  end

  def new
    @course =Course.new
  end

  def create
    @course=Course.create(params.require(:course).permit(:name,:couse_code,:course_description,:credit_hour,:ects))
    if @course.valid?
      redirect_to courses_index_path
    else
      flash[:errors]= @course.errors.full_messages
      redirect_to courses_new_path
    end
  end

  def show
    @course=Course.find(params[:id])
  end

  def edit
    @course=Course.find(params[:id])
  end

  def update
    @course=Course.find(params.require(:course).permit(:id)[:id])
    @course.update(params.require(:course).permit(:name,:couse_code,:course_description,:credit_hour,:ects))
  end

  def destroy
    @course=Course.find(params[:id])
    @course.destroy
    @enrolled=Enrollment.find_by({"course_id":id})
    @enrolled.destory
    redirect_to courses_index_path
  end
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
    def index
      @enrollments=Enrollment.all
      
      @st=[]
      for key in @enrollments do
          @st.push([Student.find(key.student_id),Course.find(key.course_id)])
      end
    end

    def new
      @enrollment=Enrollment.new
    end

    def create
      @enrollment=Enrollment.create(params.require(:enrollment).permit(:course_id,:student_id))
      @added=@enrollment.course.name
      redirect_to enrollments_index_path(@added)
    end

    def destroy
      @enrollment= Enrollment.find(params[:id])
      @student=@enrollment.student
      @enrollment.destroy
      redirect_to students_show_path({"id"=>@student.id})
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @students =Student.all

  end

  def new
    @student=Student.new
  end

  def create
    @student=Student.create(params.require(:student).permit(:full_name,:id_num,:sex,:department,:compus,:dob))
    if @student.valid?
      redirect_to students_index_path
    else
      flash[:errors]= @student.errors.full_messages
      redirect_to students_new_path
    end
  end

  def show
    @student=Student.find(params[:id])
  end

  def edit
    @student=Student.find(params[:id])
  end

  def update
    @student=Student.find(params.require(:student).permit(:id)[:id])
    @student.update(params.require(:student).permit(:full_name,:id_num,:sex,:department,:compus,:dob))
  end

  def destroy
    @student=Student.find(params[:id])
    @student.destroy
    @enrolled=Enrollment.find_by({"student_id":id})
    @enrolled.destory
    redirect_to students_index_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/courses/destroy.html.erb
<h1>Courses#destroy</h1>
<p>Find me in app/views/courses/destroy.html.erb</p>

<h1 class="text-muted"><%= @course.name %>'s page</h1>

<h2 class="btn btn-primary">name :<%= @course.name%> </h2>
<h2>couse_code :<%= @course.couse_code%> </h2>
<h2>course_description :<%= @course.course_description%> </h2>
<h2>credit_hour :<%= @course.credit_hour%> </h2>
<h2>ects :<%= @course.ects%> </h2>

<h1>HAS BEEN REMOVED!!</h1>

app/views/enrollments/destroy.html.erb
<h1>Enrollments#destroy</h1>
<p>Find me in app/views/enrollments/destroy.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudentKit</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/destroy.html.erb
<html lang="en">
<!DOCTYPE html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
        <link rel="stylesheet" href="../static/css/font-awesome.min.css">
        <link rel="stylesheet" href="../static/css/bootstrap.css">   
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
        <title>Bootstrap Sandbox</title>

        <!--INLINE CSS-->
        <style>
        
        </style>
        
        <body>

            <!--Nav Bar-->
            <nav class="navbar navbar-dark bg-dark navbar-expand-sm p-0">
                <div class="container text-sm">
                    <button class="navbar-toggler" data-toggle="collapse" data-target="#nav">
                        <i class="navbar-toggler-icon"></i> 
                    </button>
                    <a href="" class="navbar-brand" >AAiT Student Management Kit</a>
                    <div class="navbar-collapse collapse" id="nav">
                        <div class="navbar-nav">
                            <div class="nav-item px-2"><a class="nav-link" href="">Dashbord</a></div>
                            <div class="nav-item px-2"><a class="nav-link" href="/students/new">Studnets</a></div>
                            <div class="nav-item px-2"><a class="nav-link" href="/courses/new">Courses</a></div>
                            <div class="nav-item px-2"><a class="nav-link" href="/enrollments/new">Enrollments</a></div>
                        </div>
                    </div>
                </div>
            </nav>
                        <nav class="navbar navbar-info bg-info navbar-expand-sm py-1">
                <div class="container">
                    <h1 class="navbar-brand text-light">
                        <i class="fa fa-gear "></i> Student Profile
                    </h1>
                </div>
            </nav>

            <section>
                <div class="container my-4">
                    <div class="row">
                        <div class="col-sm-9">
                            <div class="card">
                                <div class="card">
                                    <div class="card-header">
                                        <h5 class="card-title"><%= @student.full_name %>'s Profile</h5>
                                    </div>
                                    <div class="card-body">
                                            <div class="form-group">
                                                <label for="">Name</label>
                                                <input readonly type="text" value="<%= @student.full_name%> " class="form-control">
                                            </div>
                                            <div class="form-group">
                                                <label for="">ID Number</label>
                                                <input readonly type="text" value="<%= @student.id_num%> " class="form-control">
                                            </div>
                                            <div class="form-group">
                                                <label for="">Sex</label>
                                                <input readonly type="text" value="<%= @student.sex%> " class="form-control">
                                            </div>
                                            <div class="form-group">
                                                <label for="">Department</label>
                                                <input readonly type="text" value="<%= @student.department%> " class="form-control">
                                            </div>
                                            <div class="form-group">
                                                <label for="">Compus</label>
                                                <input readonly type="text" value="<%= @student.compus%> " class="form-control">
                                            </div>
                                            <div class="form-group">
                                                <label for="">DOB</label>
                                                <input readonly type="text" value="<%= @student.dob%> " class="form-control">
                                            </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-3 ml-auto">
                            <div class="row">
                                <div class="col-sm-12">
                                    <button class="btn btn-info w-100 mt-4">
                                        <%= link_to "Edit Student", students_edit_path({"id"=>@student.id}) %>  
                                    </button>
                                </div>
                                <div class="col-sm-12">
                                    <button class="btn btn-success w-100 mt-2">
                                        <%= link_to "Delete Account", students_destroy_path({"id"=>@student.id}) %>
                                    </button>
                                </div>
                                <div class="col-sm-12">
                                    <button class="btn btn-warning w-100 mt-2" >
                                        <%= link_to "Register Course",enrollments_new_path,method: :get %>
                                    </button>
                                </div>
                            </div>
                            <div class="row mt-4 ml-auto border pb-4">
                                <div class="bg-success w-100 p-4 m-2 text-center pt-0 text-warning h4 d-block">Enrolled Courses</div>
                                <div class="col-sm-12 ">
                                    <% @student.enrollments.each do |enrollment| %>
                                        <div class="text-dark btn btn-outline-danger w-100 "><%=  enrollment.course.name %>
                                        <span class="text-danger"><%= link_to "Drop Enrollment",enrollments_destroy_path({"id"=>enrollment.id}),method: :delete %></span>
                                        </div>
                                    <% end %>
                                </div>
                                
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            <footer class="bg-dark py-4 text-center mt-4">
                <span class="text-muted">copyright &copy; 2017 Blogen</span>
            </footer>

          
        </body>
                
        <script src="../static/js/jquery-3.3.1.js"></script>
        <script src="../static/js/popper.min.js"></script>
        <script src="../static/js/bootstrap.min.js"></script>
        <script src="../static/js/navbar-fixed.js"></script>
</html>

app/views/students/show.html.erb
<html lang="en">
<!DOCTYPE html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
        <link rel="stylesheet" href="../static/css/font-awesome.min.css">
        <link rel="stylesheet" href="../static/css/bootstrap.css">   
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
        <title>Bootstrap Sandbox</title>

        <!--INLINE CSS-->
        <style>
        
        </style>
        
        <body>

            <!--Nav Bar-->
            <nav class="navbar navbar-dark bg-dark navbar-expand-sm p-0">
                <div class="container text-sm">
                    <button class="navbar-toggler" data-toggle="collapse" data-target="#nav">
                        <i class="navbar-toggler-icon"></i> 
                    </button>
                    <a href="" class="navbar-brand" >AAiT Student Management Kit</a>
                    <div class="navbar-collapse collapse" id="nav">
                        <div class="navbar-nav">
                            <div class="nav-item px-2"><a class="nav-link" href="">Dashbord</a></div>
                            <div class="nav-item px-2"><a class="nav-link" href="/students/index">Studnets</a></div>
                            <div class="nav-item px-2"><a class="nav-link" href="/courses/index">Courses</a></div>
                            <div class="nav-item px-2"><a class="nav-link" href="/enrollments/index">Enrollments</a></div>
                        </div>
                    </div>
                </div>
            </nav>
                        <nav class="navbar navbar-info bg-info navbar-expand-sm py-1">
                <div class="container">
                    <h1 class="navbar-brand text-light">
                        <i class="fa fa-gear "></i> Student Profile
                    </h1>
                </div>
            </nav>

            <section>
                <div class="container my-4">
                    <div class="row">
                        <div class="col-sm-9">
                            <div class="card">
                                <div class="card">
                                    <div class="card-header">
                                        <h5 class="card-title"><%= @student.full_name %>'s Profile</h5>
                                    </div>
                                    <div class="card-body">
                                            <div class="form-group">
                                                <label for="">Name</label>
                                                <input readonly type="text" value="<%= @student.full_name%> " class="form-control">
                                            </div>
                                            <div class="form-group">
                                                <label for="">ID Number</label>
                                                <input readonly type="text" value="<%= @student.id_num%> " class="form-control">
                                            </div>
                                            <div class="form-group">
                                                <label for="">Sex</label>
                                                <input readonly type="text" value="<%= @student.sex%> " class="form-control">
                                            </div>
                                            <div class="form-group">
                                                <label for="">Department</label>
                                                <input readonly type="text" value="<%= @student.department%> " class="form-control">
                                            </div>
                                            <div class="form-group">
                                                <label for="">Compus</label>
                                                <input readonly type="text" value="<%= @student.compus%> " class="form-control">
                                            </div>
                                            <div class="form-group">
                                                <label for="">DOB</label>
                                                <input readonly type="text" value="<%= @student.dob%> " class="form-control">
                                            </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-3 ml-auto">
                            <div class="row">
                                <div class="col-sm-12">
                                    <button class="btn btn-info w-100 mt-4">
                                        <%= link_to "Edit Student", students_edit_path({"id"=>@student.id}) %>  
                                    </button>
                                </div>
                                <div class="col-sm-12">
                                    <button class="btn btn-success w-100 mt-2">
                                        <%= link_to "Delete Account", students_destroy_path({"id"=>@student.id}) %>
                                    </button>
                                </div>
                                <div class="col-sm-12">
                                    <button class="btn btn-warning w-100 mt-2" >
                                        <%= link_to "Register Course",enrollments_new_path,method: :get %>
                                    </button>
                                </div>
                            </div>
                            <div class="row mt-4 ml-auto border pb-4">
                                <div class="bg-success w-100 p-4 m-2 text-center pt-0 text-warning h4 d-block">Enrolled Courses</div>
                                <div class="col-sm-12 ">
                                    <% @student.enrollments.each do |enrollment| %>
                                        <div class="text-dark btn btn-outline-danger w-100 "><%=  enrollment.course.name %>
                                        <span class="text-danger"><%= link_to "Drop Enrollment",enrollments_destroy_path({"id"=>enrollment.id}),method: :delete %></span>
                                        </div>
                                    <% end %>
                                </div>
                                
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            <footer class="bg-dark py-4 text-center mt-4">
                <span class="text-muted">copyright &copy; 2017 Blogen</span>
            </footer>

          
        </body>
                
        <script src="../static/js/jquery-3.3.1.js"></script>
        <script src="../static/js/popper.min.js"></script>
        <script src="../static/js/bootstrap.min.js"></script>
        <script src="../static/js/navbar-fixed.js"></script>
</html>

app/views/students/update.html.erb
<html lang="en">
<!DOCTYPE html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
        <link rel="stylesheet" href="../static/css/font-awesome.min.css">
        <link rel="stylesheet" href="../static/css/bootstrap.css">   
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
        <title>Bootstrap Sandbox</title>

        <!--INLINE CSS-->
        <style>
        
        </style>
        
        <body>

            <!--Nav Bar-->
            <nav class="navbar navbar-dark bg-dark navbar-expand-sm p-0">
                <div class="container text-sm">
                    <button class="navbar-toggler" data-toggle="collapse" data-target="#nav">
                        <i class="navbar-toggler-icon"></i> 
                    </button>
                    <a href="" class="navbar-brand" >AAiT Student Management Kit</a>
                    <div class="navbar-collapse collapse" id="nav">
                        <div class="navbar-nav">
                            <div class="nav-item px-2"><a class="nav-link" href="">Dashbord</a></div>
                            <div class="nav-item px-2"><a class="nav-link" href="/students/index">Studnets</a></div>
                            <div class="nav-item px-2"><a class="nav-link" href="/courses/index">Courses</a></div>
                            <div class="nav-item px-2"><a class="nav-link" href="/enrollments/index">Enrollments</a></div>
                        </div>
                    </div>
                </div>
            </nav>
                        <nav class="navbar navbar-info bg-info navbar-expand-sm py-1">
                <div class="container">
                    <h1 class="navbar-brand text-light">
                        <i class="fa fa-gear "></i> Student Profile
                    </h1>
                </div>
            </nav>

            <section>
                <div class="container my-4">
                    <div class="row">
                        <div class="col-sm-9">
                            <div class="card">
                                <div class="card">
                                    <div class="card-header">
                                        <h5 class="card-title"><%= @student.full_name %>'s Profile</h5>
                                <div class="alert p-3 border alert-success alert-dismissible fade show"> 
                                                <%= @student.full_name %>'s accout has been successfully updated 
                                                <strong class="justify-content-end btn close " data-dismiss="alert">&times;</strong>
                                            </div>           
                                    </div>
                                    <div class="card-body">
                                            <div class="form-group">
                                                <label for="">Name</label>
                                                <input readonly type="text" value="<%= @student.full_name%> " class="form-control">
                                            </div>
                                            <div class="form-group">
                                                <label for="">ID Number</label>
                                                <input readonly type="text" value="<%= @student.id_num%> " class="form-control">
                                            </div>
                                            <div class="form-group">
                                                <label for="">Sex</label>
                                                <input readonly type="text" value="<%= @student.sex%> " class="form-control">
                                            </div>
                                            <div class="form-group">
                                                <label for="">Department</label>
                                                <input readonly type="text" value="<%= @student.department%> " class="form-control">
                                            </div>
                                            <div class="form-group">
                                                <label for="">Compus</label>
                                                <input readonly type="text" value="<%= @student.compus%> " class="form-control">
                                            </div>
                                            <div class="form-group">
                                                <label for="">DOB</label>
                                                <input readonly type="text" value="<%= @student.dob%> " class="form-control">
                                            </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-3 ml-auto">
                            <div class="row">
                                <div class="col-sm-12">
                                    <button class="btn btn-info w-100 mt-4">
                                        <%= link_to "Edit Student", students_edit_path({"id"=>@student.id}) %>  
                                    </button>
                                </div>
                                <div class="col-sm-12">
                                    <button class="btn btn-success w-100 mt-2">
                                        <%= link_to "Delete Account", students_destroy_path({"id"=>@student.id}) %>
                                    </button>
                                </div>
                                <div class="col-sm-12">
                                    <button class="btn btn-warning w-100 mt-2" >
                                        <%= link_to "Register Course",enrollments_new_path,method: :get %>
                                    </button>
                                </div>
                            </div>
                            <div class="row mt-4 ml-auto border pb-4">
                                <div class="bg-success w-100 p-4 m-2 text-center pt-0 text-warning h4 d-block">Enrolled Courses</div>
                                <div class="col-sm-12 ">
                                    <% @student.enrollments.each do |enrollment| %>
                                        <div class="text-dark btn btn-outline-danger w-100 "><%=  enrollment.course.name %>
                                        <span class="text-danger"><%= link_to "Drop Enrollment",enrollments_destroy_path({"id"=>enrollment.id}),method: :delete %></span>
                                        </div>
                                    <% end %>
                                </div>
                                
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            <footer class="bg-dark py-4 text-center mt-4">
                <span class="text-muted">copyright &copy; 2017 Blogen</span>
            </footer>

          
        </body>
                
        <script src="../static/js/jquery-3.3.1.js"></script>
        <script src="../static/js/popper.min.js"></script>
        <script src="../static/js/bootstrap.min.js"></script>
        <script src="../static/js/navbar-fixed.js"></script>
</html>